### ISSUE TITLE
삼성폰에서 안드로이드 11에서 앱 중단되는 문제

### ISSUE THREAD

**Issue by Minimoa** [Hwarang-Go/MINDSCOPE_Client-master#22]
![image](https://user-images.githubusercontent.com/13061461/107180406-fa3e9a00-6a1b-11eb-9f12-cce1ca4cb465.png)
![image](https://user-images.githubusercontent.com/13061461/107180422-03c80200-6a1c-11eb-8aec-8eb4ab4ab966.png)

안드로이드 11에서 카메라/마이크 권한의 경우 `이번만 허용`  옵션, 앱이 포그라운드에 있는 경우에만 허용되고, 일정 시간이 지나면 권한 해제되도록 변경되었음

마이크 권한이 해제되면서 오디오 녹음이 막혀서 앱이 중단되는 것으로 보임 
또 앱이 중단되면서 종료되어 알림도 오지 않는 것 같음 

```
2021-02-08 14:40:05.382 21541-21541/kr.ac.inha.mindscope E/IAudioFlinger: createRecord returned error -1
2021-02-08 14:40:05.382 21541-21541/kr.ac.inha.mindscope E/AudioRecord: createRecord_l(375): AudioFlinger could not create record track, status: -1
2021-02-08 14:40:05.382 21541-21541/kr.ac.inha.mindscope E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -1.
2021-02-08 14:40:05.383 21541-21541/kr.ac.inha.mindscope E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
2021-02-08 14:40:05.383 21541-21541/kr.ac.inha.mindscope D/AndroidRuntime: Shutting down VM
2021-02-08 14:40:05.384 21541-21541/kr.ac.inha.mindscope E/AndroidRuntime: FATAL EXCEPTION: main
    Process: kr.ac.inha.mindscope, PID: 21541
    java.lang.IllegalStateException: startRecording() called on an uninitialized AudioRecord.
        at android.media.AudioRecord.startRecording(AudioRecord.java:1142)
        at be.tarsos.dsp.io.android.AudioDispatcherFactory.fromDefaultMicrophone(Unknown Source:44)
        at kr.ac.inha.mindscope.services.AudioFeatureRecorder.<init>(AudioFeatureRecorder.java:34)
        at kr.ac.inha.mindscope.services.MainService$1.run(MainService.java:218)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by Minimoa** [comment]
https://kangraemin.github.io/android/2020/07/17/android-11/
