### ISSUE TITLE
gRPC Issue

### ISSUE THREAD

**Issue by Hwarang-Go** [Hwarang-Go/MINDSCOPE_Client-master#3]
With the error below, data is not uploaded to the ET db.

galaxy s9 (android 10)
```
2020-08-04 10:03:01.300 797-2832/kr.ac.inha.mindscope E/CustomSensorsService: DataCollectorService.setUpDataSubmissionThread() exception: UNAVAILABLE: End of stream or IOException
2020-08-04 10:03:01.300 797-2832/kr.ac.inha.mindscope W/System.err: io.grpc.StatusRuntimeException: UNAVAILABLE: End of stream or IOException
2020-08-04 10:03:01.300 797-2832/kr.ac.inha.mindscope W/System.err:     at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233)
2020-08-04 10:03:01.300 797-2832/kr.ac.inha.mindscope W/System.err:     at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214)
2020-08-04 10:03:01.300 797-2832/kr.ac.inha.mindscope W/System.err:     at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139)
2020-08-04 10:03:01.300 797-2832/kr.ac.inha.mindscope W/System.err:     at inha.nsl.easytrack.ETServiceGrpc$ETServiceBlockingStub.submitDataRecord(ETServiceGrpc.java:1159)
2020-08-04 10:03:01.300 797-2832/kr.ac.inha.mindscope W/System.err:     at kr.ac.inha.mindscope.services.MainService$2.lambda$run$0$MainService$2(MainService.java:303)
2020-08-04 10:03:01.301 797-2832/kr.ac.inha.mindscope W/System.err:     at kr.ac.inha.mindscope.services.-$$Lambda$MainService$2$gxUhatCE2sDBxsksqYNgCo8x38s.run(Unknown Source:2)
2020-08-04 10:03:01.301 797-2832/kr.ac.inha.mindscope W/System.err:     at java.lang.Thread.run(Thread.java:919)

2020-08-04 10:11:01.804 797-5204/kr.ac.inha.mindscope E/CustomSensorsService: DataCollectorService.setUpDataSubmissionThread() exception: UNAVAILABLE: Failed parsing HTTP/2
2020-08-04 10:11:01.805 797-5204/kr.ac.inha.mindscope W/System.err: io.grpc.StatusRuntimeException: UNAVAILABLE: Failed parsing HTTP/2
2020-08-04 10:11:01.810 797-5204/kr.ac.inha.mindscope W/System.err:     at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233)
2020-08-04 10:11:01.811 797-5204/kr.ac.inha.mindscope W/System.err:     at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214)
2020-08-04 10:11:01.812 797-5204/kr.ac.inha.mindscope W/System.err:     at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139)
2020-08-04 10:11:01.813 797-5204/kr.ac.inha.mindscope W/System.err:     at inha.nsl.easytrack.ETServiceGrpc$ETServiceBlockingStub.submitDataRecord(ETServiceGrpc.java:1159)
2020-08-04 10:11:01.813 797-5204/kr.ac.inha.mindscope W/System.err:     at kr.ac.inha.mindscope.services.MainService$2.lambda$run$0$MainService$2(MainService.java:303)
2020-08-04 10:11:01.814 797-5204/kr.ac.inha.mindscope W/System.err:     at kr.ac.inha.mindscope.services.-$$Lambda$MainService$2$gxUhatCE2sDBxsksqYNgCo8x38s.run(Unknown Source:2)
2020-08-04 10:11:01.814 797-5204/kr.ac.inha.mindscope W/System.err:     at java.lang.Thread.run(Thread.java:919)
```

Galaxy Note 8 (android 9)
```
2020-08-05 02:54:34.206 7183-12793/kr.ac.inha.mindscope E/CustomSensorsService: DataCollectorService.setUpDataSubmissionThread() exception: UNKNOWN: Exception calling application: 'NoneType' object is not subscriptable
2020-08-05 02:54:34.222 7183-12793/kr.ac.inha.mindscope W/System.err: io.grpc.StatusRuntimeException: UNKNOWN: Exception calling application: 'NoneType' object is not subscriptable
2020-08-05 02:54:34.223 7183-12793/kr.ac.inha.mindscope W/System.err:     at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233)
2020-08-05 02:54:34.224 7183-12793/kr.ac.inha.mindscope W/System.err:     at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214)
2020-08-05 02:54:34.224 7183-12793/kr.ac.inha.mindscope W/System.err:     at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139)
2020-08-05 02:54:34.225 7183-12793/kr.ac.inha.mindscope W/System.err:     at inha.nsl.easytrack.ETServiceGrpc$ETServiceBlockingStub.submitDataRecord(ETServiceGrpc.java:1159)
2020-08-05 02:54:34.225 7183-12793/kr.ac.inha.mindscope W/System.err:     at kr.ac.inha.mindscope.services.MainService$2.lambda$run$0$MainService$2(MainService.java:303)
2020-08-05 02:54:34.226 7183-12793/kr.ac.inha.mindscope W/System.err:     at kr.ac.inha.mindscope.services.-$$Lambda$MainService$2$gxUhatCE2sDBxsksqYNgCo8x38s.run(Unknown Source:2)
2020-08-05 02:54:34.227 7183-12793/kr.ac.inha.mindscope W/System.err:     at java.lang.Thread.run(Thread.java:764)

2020-08-05 03:00:34.162 7183-14165/kr.ac.inha.mindscope E/CustomSensorsService: DataCollectorService.setUpDataSubmissionThread() exception: UNAVAILABLE: Failed parsing HTTP/2
2020-08-05 03:00:34.162 7183-14165/kr.ac.inha.mindscope W/System.err: io.grpc.StatusRuntimeException: UNAVAILABLE: Failed parsing HTTP/2
2020-08-05 03:00:34.164 7183-14165/kr.ac.inha.mindscope W/System.err:     at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233)
2020-08-05 03:00:34.165 7183-14165/kr.ac.inha.mindscope W/System.err:     at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214)
2020-08-05 03:00:34.166 7183-14165/kr.ac.inha.mindscope W/System.err:     at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139)
2020-08-05 03:00:34.167 7183-14165/kr.ac.inha.mindscope W/System.err:     at inha.nsl.easytrack.ETServiceGrpc$ETServiceBlockingStub.submitDataRecord(ETServiceGrpc.java:1159)
2020-08-05 03:00:34.168 7183-14165/kr.ac.inha.mindscope W/System.err:     at kr.ac.inha.mindscope.services.MainService$2.lambda$run$0$MainService$2(MainService.java:303)
2020-08-05 03:00:34.169 7183-14165/kr.ac.inha.mindscope W/System.err:     at kr.ac.inha.mindscope.services.-$$Lambda$MainService$2$gxUhatCE2sDBxsksqYNgCo8x38s.run(Unknown Source:2)
2020-08-05 03:00:34.169 7183-14165/kr.ac.inha.mindscope W/System.err:     at java.lang.Thread.run(Thread.java:764)
```

**Comment by qobiljon** [comment]
I'll check as soon as I'm back from the immigration office today

**Comment by Hwarang-Go** [comment]
Thank you!

2020년 8월 5일 (수) 오전 10:38, Kobiljon Toshnazarov (Kevin) <
notifications@github.com>님이 작성:

**Comment by qobiljon** [comment]
I'm trying to reproduce the same issue but failing. I cannot reproduce the issue you mentioned with galaxy s8 device.

1. And may I ask why you think it's because of a phone model?
2. Which phone was it? what time did it happen?
3. What data source caused the issue? (because in my case, loudness and app usage is being submitted and causing no exceptions)
